### ISSUE TITLE
Node.js v4.0.0

### ISSUE THREAD

**Issue by Nousemusic** [KraigM/homebridge-harmonyhub#10]
Great Plugin. Thank you.

The Harmony Hub plugin for homebridge seems not to work with Node.js v4.0.0. Is that right?

And if so, will the be a new version to work with Node.js v4.0.0.?

Thank you in advance.

**Comment by KraigM** [comment]
Its the dependencies who seem to have issues with it.  I used nvm to downgrade to 0.12.x and it works like a champ.

**Comment by JBX77** [comment]
Can I have two versions of node installed at the same time? I need >4.0.0 for all my other Homebridge plugins. Are you planning on upgrading to 4.0.0 soon?
Thanks.

**Comment by KraigM** [comment]
Try the version I just released last night (0.1.1). We are now using the latest of all the packages except for a special version of lfx that is needed.

**Comment by JBX77** [comment]
Installs fine now. Thank you!

**Comment by Nousemusic** [comment]
If I have an older version of the plugin running,how can I update to 0.1.1? Do I have to install it again via npm install -g homebridge-harmonyhub?

Thank you in advance.

**Comment by KraigM** [comment]
@Nousemusic Yes you just rerun the install and it will install the new version `npm install -g homebridge-harmonyhub`

**Comment by Nousemusic** [comment]
Great! Thank you for your fast help, perfect.
