### ISSUE TITLE
Error with Alpha 0.3.0-alpha.2. „Unhandled "error" event. (XMPP authentication failure)“

### ISSUE THREAD

**Issue by Nastras** [KraigM/homebridge-harmonyhub#107]
Hello KraigM,

very cool that you develop your plugin still further. Thank you!

I have installed your HarmonyHub beta Alpha 0.3.0-alpha.2. Since the Homebridge crashes every hour with this error.

I hope you can fix the error?

Oct 14 03:39:23 Server homebridge[6836]: events.js:187
Oct 14 03:39:23 Server homebridge[6836]:       throw err;
Oct 14 03:39:23 Server homebridge[6836]:       ^
Oct 14 03:39:23 Server homebridge[6836]: Error: Unhandled "error" event. (XMPP authentication failure)
Oct 14 03:39:23 Server homebridge[6836]:     at Client.emit (events.js:185:19)
Oct 14 03:39:23 Server homebridge[6836]:     at Client._handleAuthState (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:298:10)
Oct 14 03:39:23 Server homebridge[6836]:     at Client._handleStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:234:12)
Oct 14 03:39:23 Server homebridge[6836]:     at Client.onStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:222:8)
Oct 14 03:39:23 Server homebridge[6836]:     at emitOne (events.js:115:13)
Oct 14 03:39:23 Server homebridge[6836]:     at Connection.emit (events.js:210:7)
Oct 14 03:39:23 Server homebridge[6836]:     at Connection.onStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:369:10)
Oct 14 03:39:23 Server homebridge[6836]:     at StreamParser.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:226:10)
Oct 14 03:39:23 Server homebridge[6836]:     at emitOne (events.js:115:13)
Oct 14 03:39:23 Server homebridge[6836]:     at StreamParser.emit (events.js:210:7)
Oct 14 03:39:23 Server homebridge[6836]:     at SaxLtx.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
Oct 14 03:39:23 Server homebridge[6836]:     at emitOne (events.js:115:13)
Oct 14 03:39:23 Server homebridge[6836]:     at SaxLtx.emit (events.js:210:7)
Oct 14 03:39:23 Server homebridge[6836]:     at SaxLtx._handleTagOpening (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:28:22)
Oct 14 03:39:23 Server homebridge[6836]:     at SaxLtx.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
Oct 14 03:39:23 Server homebridge[6836]:     at StreamParser.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
Oct 14 03:39:23 Server homebridge[6836]:     at Connection.onData (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:305:17)
Oct 14 03:39:23 Server homebridge[6836]:     at emitOne (events.js:120:20)
Oct 14 03:39:23 Server homebridge[6836]:     at Socket.emit (events.js:210:7)
Oct 14 03:39:23 Server homebridge[6836]:     at addChunk (_stream_readable.js:266:12)
Oct 14 03:39:23 Server homebridge[6836]:     at readableAddChunk (_stream_readable.js:253:11)
Oct 14 03:39:23 Server homebridge[6836]:     at Socket.Readable.push (_stream_readable.js:211:10)
Oct 14 03:39:23 Server homebridge[6836]:     at TCP.onread (net.js:585:20)
Oct 14 03:39:23 Server systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Oct 14 03:39:23 Server systemd[1]: homebridge.service: Unit entered failed state.
Oct 14 03:39:23 Server systemd[1]: homebridge.service: Failed with result 'exit-code'.
Oct 14 03:39:33 Server systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.

**Comment by imsturmdernacht** [comment]
Same here,

Error: Unhandled "error" event. (XMPP authentication failure) while running the harmonyhub plugin and
also during installation of the plugin:

npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>

npm WARN deprecated node-xmpp-jid@2.3.0: use @xmpp/jid package <https://www.npmjs.com/package/@xmpp/jid>

I updated node-xmpp-stanza to 1.1.1 with sudo npm -g install node-xmpp-stanza and it seems 
the situation is a little better now. With 1.1.1 homebridge crashes only two times a day.

The node-xmpp-stanza developer says: XMPP authentication failure means the user or password is not good.

Which username or password?

Seems it's a neverending story.... does anyone have a sollution?

Greets Oli
