### ISSUE TITLE
Harmony Link End of Service Notice

### ISSUE THREAD

**Issue by Hackashaq666** [KraigM/homebridge-harmonyhub#108]
I saw you are working on Link Hub support.
I received an email fron Logitech last month:

This is an important update regarding your Harmony Link. On March 16, 2018, Logitech will discontinue service and support for Harmony Link. Your Harmony Link will no longer function after this date.

**Comment by Hackashaq666** [comment]
They gave me a 35% off code for a new hub remote.

**Comment by ersan** [comment]
@Hackashaq666 if you haven't seen already, they are giving all Link owners a free hub now.

**Comment by Hackashaq666** [comment]
Thanks fot the info!  Will be happy if they come through with new hub🤘🏻

**Comment by Hackashaq666** [comment]
Received my replacement hub from Logitech.
