### ISSUE TITLE
Node reversioned?

### ISSUE THREAD

**Issue by amro** [KraigM/homebridge-harmonyhub#12]
Hey Kraig. Thanks for writing this plugin (and the Nest plugin).

I'm new to nodejs. It looks like it was reversioned recently?

    npm install -g homebridge-harmonyhub
    npm WARN engine node-stringprep@0.7.3: wanted: {"node":">=0.8 <=0.12"} (current: {"node":"5.3.0","npm":"3.3.12"})

What's the right way to deal with this?

**Comment by KraigM** [comment]
Warnings are ok if it works, but I have not had luck with newer versions of node (others have but I haven't).  So as long as it installed and works then be happy you are one of the lucky ones :-) .  If not, then you can use nvm to change your version of node to 0.12.x.

**Comment by amro** [comment]
I see now that in the package you've set >=0.12.x. So npm isn't doing the version check properly. booo.
