### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by aiordanescu** [KraigM/homebridge-harmonyhub#14]
pi@raspberrypi:~ $ sudo npm install -g homebridge-harmonyhub
loadDep:harmonyhubjs-disc ▄ ╢████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! addLocal Could not install /tmp/npm-5525-0540c1e2/git-cache-d80f2cf1/2a8f1303712c6b6f10eaf49c80f6db7ef21e4336
npm ERR! Linux 4.1.13+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-harmonyhub"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2

npm ERR! No version provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

**Comment by KraigM** [comment]
what is the log file?

**Comment by KraigM** [comment]
It might be related to changes that @swissmanu is apparently making (see #13)

**Comment by elseym** [comment]
can be fixed with #13

**Comment by KraigM** [comment]
Try the version I just released last night (0.1.1). We are now using the latest of all the packages except for a special version of lfx that is needed.

**Comment by aiordanescu** [comment]
That worked, thank you!
