### ISSUE TITLE
the plugin will not install

### ISSUE THREAD

**Issue by thomasbruce** [KraigM/homebridge-harmonyhub#16]
I'm a bit of a noob when it comes to linux and coding, but I managed to install homebridge and the netatmo plugin on my new raspberry pi 2 model b and it works fine.

When I try to install the harmonyhub plugin i get errors and it will not install:

sudo npm install -g homebridge-harmonyhub
npm WARN engine node-stringprep@0.7.3: wanted: {"node":">=0.8 <=0.12"} (current: {"node":"5.3.0","npm":"3.3.12"})
npm ERR! addLocal Could not install /tmp/npm-868-ff7aef65/git-cache-5cc7fec56addf09611cbc6d6c9ad2b3b/2a8f1303712c6b6f10eaf49c80f6db7ef21e4336
npm WARN install Couldn't install optional dependency: No version provided in package.json

Is there a bug or is it just me thats too stupid to understand :)

Hope you can help!

Thomas

**Comment by JBX77** [comment]
Hi

It says you have node 5.3.0 but you need <0.12.
 https://github.com/KraigM/homebridge-harmonyhub/issues/10

**Comment by KraigM** [comment]
Try the version I just released last night (0.1.1). We are now using the latest of all the packages except for a special version of lfx that is needed.

**Comment by thomasbruce** [comment]
Thanks for helping me :)

Tried again today and it all worked fine!

**Comment by JBX77** [comment]
Installs fine now. Thank you!
