### ISSUE TITLE
Multipal Hub Support  

### ISSUE THREAD

**Issue by EnigmaFx** [KraigM/homebridge-harmonyhub#18]
Hi I Have 3 hubs in my home? it seems that this plugin only supports one hub? is there a work around for this by chance? "

**Comment by KraigM** [comment]
Duplicate of #6

**Comment by EnigmaFx** [comment]
(UPDATE) Just manually assign an ip and a different name to each hub and it works with out a hitch Confirmed and tested --->  http://d.pr/i/17Jb9

**Comment by EnigmaFx** [comment]
FYI The config File chould look something like this ---> http://d.pr/i/fyNE <---
