### ISSUE TITLE
No response when turning off activity

### ISSUE THREAD

**Issue by wormiedk** [KraigM/homebridge-harmonyhub#2]
When I turn of any activity siri says that it fails even though my harmony does turn of the tv.

I can see the following in the log
[Living Room Harmony Hub] Queue activity to -1
[Living Room Harmony Hub] Set activity to -1
It never succeeds such as when I activate my "se apple tv activity"
[Living Room Harmony Hub] Queue activity to 11233806
[Living Room Harmony Hub] Set activity to 11233806
[Living Room Harmony Hub] Finished setting activity to 11233806

**Comment by dsbudiac** [comment]
Same issue here. Any "off" activity command sent to harmony hub triggers a timeout/reconnect, even though power off was successful.

**Comment by KraigM** [comment]
As far as I know, HarmonyHub doesn't send back a response until everything has been turned off.  So from what I can tell our options are:

- Send HomeKit a success as soon as we send the signal to harmony

- We leave it like it is and it will "timeout" even though it works

- Someone figures out a way determine how to to detect that it started sending the IR signals and we mark it complete then

If anyone has any other thoughts/suggestions/theories/etc or if anyone wants to look into that last option just let me know.  If not, I will look into when I get the chance.

**Comment by wormiedk** [comment]
As the harmony hub has no idea if the command succeeds or not I would think the first option would be the best. The problem is that SIRI will assume the command failed and issue a "I have problems connecting to your devices" warning.

**Comment by dansays** [comment]
Agreed. Absent confirmation from Harmony, it seems best to assume success. It's not ideal, but it's better than always returning a timeout error.

**Comment by realdannys** [comment]
Can I third the request for an automatic success on turning things off, it spoils the magic somewhat when Siri throws back an error.

Its strange that it knows its turned everything on ok though?

**Comment by KraigM** [comment]
I updated it to tell Siri it was complete once it makes its way to the front of the execution queue, starts the request to the hub, and it has been at least 2 seconds without any error.  If it finishes in that two seconds, then it will respond to Siri immediately (as will errors).

**Comment by KraigM** [comment]
I also fixed the other issue noted by @wormiedk, where turning it off always causes reconnect.  The third party module was looking for '-1' instead of -1 even though it sent -1 as '-1'. (/facepalm)

**Comment by KraigM** [comment]
This has been released under 0.1.0

**Comment by DJay1** [comment]
As an absolut newbie I have to ask how I update the Plugin on OS X with the Terminal?
And not loose my config.
Thanks in advance.

**Comment by KraigM** [comment]
npm update -g homebridge-harmonyhub

**Comment by KraigM** [comment]
then just restart homebridge

**Comment by DJay1** [comment]
Thx. There were a few strange messages but seems to work. Sorry I was to fast closing the terminal so I couldn't make a screenshot.
Don't want to bother.. but is there a Terminal command to stop homebridge so I can restart again? When I only start Homebridge it gives me some errors like it's already running. Thanks again for your patience and kind help.

**Comment by KraigM** [comment]
Really depends on how you started it

**Comment by DJay1** [comment]
Just by terminal in OS X /Users/Daniel/node_modules/homebridge/bin/homebridge
I use run a .app with a script at startup to keep the process running in background.
I'm not a pro with this so a friend helped with that.

tell application "Finder"
	do shell script "export PATH=$PATH:/usr/local/bin/; /Users/Daniel/node_modules/homebridge/bin/homebridge  > /dev/null 2>&1 &"
end tell
