### ISSUE TITLE
Can this work for multiple hubs in one house

### ISSUE THREAD

**Issue by zaphodbeeblebroxpotu** [KraigM/homebridge-harmonyhub#20]
I currently have five harmony hubs in my house - can you control multiple hubs by giving them different names in the configuration file?  How do you associate a given name with an IP?  Do you separate them by separate curly brackets?

Here is something like what my config will look like - would this be correct?
    "platforms": [
        {
            "platform": "HarmonyHub",
            "name": "TV Room Harmony Hub",
            "ip_address":"192.168.1.181"
        }
        {
            "platform": "HarmonyHub",
            "name": "Kitchen Harmony Hub",
            "ip_address":"192.168.1.132"
        }
        {
            "platform": "HarmonyHub",
            "name": "Bedroom Harmony Hub",
            "ip_address":"192.168.1.139"
        }
    ]

**Comment by KraigM** [comment]
You need commas between items in a list (in other words between your close curly and open curlies). Other then that, yes others have gotten multiples to work that way. There is an issue written up already, to better support multiple hubs.

**Comment by KraigM** [comment]
Here is the other item #6  

Hopefully my above statement helps but if not post any further questions on that item if you can.  That way there is one place for people needing help with multiple hubs, plus the people on that item are other people who have multiple hubs so they can also help.

**Comment by zaphodbeeblebroxpotu** [comment]
So just to close the loop and to help others in the future - this should work?  (consolidated onto fewer lines to make it easier to read)

"platforms": [
 { "platform": "HarmonyHub", "name": "TV Room Harmony Hub", "ip_address":"192.168.1.181" },
 { "platform": "HarmonyHub", "name": "Kitchen Harmony Hub", "ip_address":"192.168.1.132" },
 { "platform": "HarmonyHub", "name": "Bedroom Harmony Hub", "ip_address":"192.168.1.139" }
 ]

**Comment by KraigM** [comment]
Yes
