### ISSUE TITLE
Mini IR Blasters dont seem to function

### ISSUE THREAD

**Issue by webpablo** [KraigM/homebridge-harmonyhub#32]
I was able to set everything up and fire an activity through Homekit. The only problem is every device but theTV runs through a connected mini blaster and are assigned discreetly to each blaster. When I run a device with the cabinet doors closed, only the TV powers on etc. When I open the cabinet doors activities fire correctly. This seems to indicate to me that all the IR commands (even ones setup for the mini blasters only) are coming out of the main blaster? Am I missing something in my setup?

**Comment by jer78** [comment]
That's bizarre. I believe the HarmonyHub plugin just runs the command to start and stop activities and shouldn't have any control over the mini-blasters. Is the same thing happening with your remote?

**Comment by webpablo** [comment]
Yeah it's super weird. The remote itself works just fine and fires everything correctly. The problem only happens when I use homebridge with the harmony plugin.

**Comment by jer78** [comment]
I'll see if I can replicate your issue this weekend. I have some devices behind closed doors (but they are usually open for air circulation) so I've never really noticed if it happens to me too.

**Comment by KraigM** [comment]
This should only be related to the harmony hub itself and not the plugin.

That being said, I just recently figured out that mine is working (bc I moved my IR blaster when I was working on the new version and it stopped controlling some of my devices 😄). 

You can check your settings to ensure it is supposed to be using the IR blasters with the HarmonyHub app:

1. Connect to hub on app
2. Open Menu(top left corner) > Harmony Setup > Add/Edit Devices & Activities > Remote & Hub > IR Assignments
3. Now you should see all the devices. Verify that the things in your cabinet specify Mini Blasters.  If not, select and fix them

**Comment by webpablo** [comment]
interestingly enough. I tried again today and everything is working. =/ I did change the discrete IR assignments to basically send all commands to all receivers. Either way, if no other reports come in I think its safe to say we can close this issue out.
