### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by TheRealTremes** [KraigM/homebridge-harmonyhub#36]
Hello, I want to install the Harmony Hub. But it fails:
> pi@raspberrypi:~ $ sudo npm install -g homebridge-harmonyhub@0.2.0-alpha
npm WARN engine harmonyhubjs-client@1.1.8: wanted: {"npm":">=3.0.0"} (current: {"node":"0.12.1","npm":"2.5.1"})
npm ERR! fetch failed https://github.com/swissmanu/ltx.git#cdata-for-ltx-parser
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
npm ERR! fetch failed https://github.com/swissmanu/ltx.git#cdata-for-ltx-parser
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
npm ERR! fetch failed https://github.com/swissmanu/ltx.git#cdata-for-ltx-parser
npm ERR! Linux 4.4.11-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-harmonyhub@0.2.0-alpha"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! fetch failed with status code 406
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

What can I do? THX!

**Comment by jer78** [comment]
It says you need to upgrade your NPM

**Comment by TheRealTremes** [comment]
Can you please tell me how do I update NPM. thank you

**Comment by jer78** [comment]
sudo npm install npm -g

**Comment by TheRealTremes** [comment]
But I have already installed NPM.

**Comment by jer78** [comment]
It should upgrade to the latest version

**Comment by TheRealTremes** [comment]
How can I make only one upgrade?

**Comment by jer78** [comment]
What do you mean by only one upgrade?

**Comment by TheRealTremes** [comment]
npm update -g

THX for help
