### ISSUE TITLE
Two Harmonies don't work in Harmony

### ISSUE THREAD

**Issue by techyowl** [KraigM/homebridge-harmonyhub#5]
ok bad jokes asside. I have two Harmony Hubs on the same network and when I try to use your homebridge plugin it crashed the whole home bridge instance. 

error is 
<img width="475" alt="screen shot 2015-12-06 at 2 06 42 pm" src="https://cloud.githubusercontent.com/assets/16109497/11615947/df0ebd0e-9c22-11e5-98ba-3f27f2c8590c.png">

config is

<img width="202" alt="screen shot 2015-12-06 at 2 09 25 pm" src="https://cloud.githubusercontent.com/assets/16109497/11615950/fdd55fe0-9c22-11e5-924b-0c5cfcd8b240.png">

**Comment by techyowl** [comment]
Ok I found out that it only breaks it if you leave out the optional IP Address field. setting the ip up with a reservation at the router is also a good idea. all is good now.

**Comment by KraigM** [comment]
So you were able to register both?

**Comment by techyowl** [comment]
I tried to register both and it had an error saying it could not create a home kit accessory with the same UDID or something along that lines but I think that was due to both harmonies having activities named the same but controlling separate devices. so I went ahead and disabled one of them and now it runs ok.

**Comment by KraigM** [comment]
Yeah we need to setup a feature request item for supporting multiple devices better.  The original developer wrote a TODO in there but that doesn't help much lol
