### ISSUE TITLE
how to input the config.json

### ISSUE THREAD

**Issue by rogergilmore** [KraigM/homebridge-harmonyhub#7]
after I installed the homebridge-harmonyhub and I try to run homebridge I get this:

Rogers-iMac:~ roger$ homebridge
Loaded plugin: homebridge-harmonyhub
Registering platform 'homebridge-harmonyhub.HarmonyHub'
---
Couldn't find a config.json file at '/Users/roger/.homebridge/config.json'. Look at config-sample.json for examples of how to format your config.js and add your home accessories.

I know step 3 of your guide @ "https://www.npmjs.com/package/homebridge-harmonyhub" says to "Update your configuration file. See sample config.json snippet below".

What is the command to type to update the configuration file.  Thank you for your help.  Also this if my first time using npm and I do not know coding.

**Comment by KraigM** [comment]
the config.json file you have to update is the one setup as part of setting up homebridge

**Comment by KraigM** [comment]
See the Installation section of https://github.com/nfarina/homebridge

**Comment by rogergilmore** [comment]
I understand to use the sample you provided for the config.json, but how do you install it in the home directory inside .homebridge?

**Comment by KraigM** [comment]
The sample I provide was was to add to the sample config as described in  https://github.com/nfarina/homebridge

**Comment by DJay1** [comment]
@rogergilmore I'm also not a pro but try my config.json and put it in your folder. Remove the hombebridge-http oder change it to something you could use. The homebridge-harmonyhub part is at the end of it. Maybe this is a start for you to try something out. http://cl.ly/0W0t2q2W3b46
Also what helps me at the beginning if I did the json right check the content on http://jsonlint.com
Good luck.

**Comment by rogergilmore** [comment]
@DJay1 How do you get the config.json into the .homebridge folder on a mac?

**Comment by KraigM** [comment]
You should be able to just create a folder with that name. I'm not sure if it keeps showing it if you haven't turned on the "show hidden folders" (I'm a programmer so I can't survive with out it lol). 

Alternatively you can just create a non hidden folder (aka in the "roger" folder create a "homebridge" folder). Then you just have to use the start it with an extra command line option "homebridge -u ~/homebridge"

**Comment by rogergilmore** [comment]
I ran the mac script to show all hidden folders and no joy on finding the .homebridge folder.  I then tried to create one called it home bridge and added the config.json and tried the "homebridge -u ~/homebridge" script and received error "error: unknown option `-u'".  I tried to change the name of the folder I created from homebridge to .homebridge and OS X popped an error saying that folder cannot start with a "." that is reserved for system folders.  I have been doing all of this in finder.  Should I be doing it another way?

**Comment by KraigM** [comment]
... Dude... The ".homebridge" folder is not some magical folder or anything.  You have to create the folder.  I was trying to show you how to do it without a hidden folder so that you wouldn't have to enable that (since it shows you a lot of superuser things that most users don't want to see.

As far as the unknown -u option, it must be case sensitive so try -U instead.
