### ISSUE TITLE
Problem with the install?

### ISSUE THREAD

**Issue by jmaddr** [KraigM/homebridge-harmonyhub#8]
I'm having an issue with the install I can't seem to get around.  When installing homebridge-harmonyhub, I encounter all sorts of errors.  Install log attached.  Wink and a few others seem to install just fine.  

[homebridge-harmonyhub _error.txt](https://github.com/KraigM/homebridge-harmonyhub/files/60757/homebridge-harmonyhub._error.txt)

**Comment by KraigM** [comment]
I have only had success installing the dependencies node 0.8.x through 0.12.x.  I use the latest 0.12.x (0.12.8) and it works great.  To switch, I suggest nvm.

**Comment by jmaddr** [comment]
Thanks, I'll try that
